# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2bcf92816d5cbe7cc0ba563e980a88fe48b3801918ffc4370f6bf0170883ae98482bed924e3b26c630a30b1de2faeaa951cb17278fb6039dd4b4da6553902d8

test:
  secret_key_base: 18cf1ef9ec484799746b20e5ffc900df8630e3056f5aa1758134af97b8c40cd0d9cf9b34127c6a969b9d8ec9bee6d4199b5eb4099627a0b35a5be9ee3d873200

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
